### ISSUE TITLE
Remove `graphql-fragments` add `graphql-tag`

### ISSUE THREAD

**Issue by loganvolkers** [apollostack/tools-docs#35]
- `graphql-fragments` is deprecated and should be removed
 - `graphql-tag` isn't listed and seems pretty handy

I'm not sure the best way to summarize `graphql-tag` otherwise I'd make the change to the docs myself. https://github.com/apollostack/tools-docs/blob/master/tools/index.md

**Comment by stubailo** [comment]
Yes, please make the change!

I'd say `graphql-tag` is a simple library for parsing and printing GraphQL queries, as well as putting together multiple fragments into one query.
