### ISSUE TITLE
Change root to parent

### ISSUE THREAD

**Issue by Tallyb** [apollostack/tools-docs#47]
On the resolver explanation: 
http://dev.apollodata.com/tools/graphql-tools/resolvers.html
It will make much more sense if "root" argument was renamed to "parent".

**Comment by stubailo** [comment]
It's called `root` everywhere in official GraphQL docs I think, so I feel like picking a different name would add to more confusion? Although I agree `parent` is a much better name...

**Comment by Tallyb** [comment]
mmm.... I believe it is called obj in the graphqql.org http://graphql.org/learn/execution/#root-fields-resolvers
Although parent is better, there is a point in changing it to obj. I would be happy to PR it.

**Comment by helfer** [comment]
@Tallyb Renaming it to `obj` would be great (now that the GraphQL docs refer to it as that), if you have the patience to find all those references where we called it root!
